# Site
title: Kain's Notes
author: Kain
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://kainonly.com
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null

# Writing
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime

# Pagination
per_page: 10
pagination_dir: page
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

# Extensions
theme: icarus
