version: 4.0.0
variant: default
logo: /img/logo.png

head:
  favicon: /img/favicon.svg
  manifest:
    name:
    short_name:
    start_url:
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    image:
  meta:
    - ""

navbar:
  menu:
    主页: /
    手册: /document
    分类: /categories
    标签: /tags
    归档: /archives

footer:
  links:
    Download on GitHub:
      icon: fab fa-github
      url: "https://github.com/kainonly"
    "琼ICP备18004473号":
      url: "https://beian.miit.gov.cn"

article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  readtime: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    "CC BY-NC-SA 4.0": "https://creativecommons.org/licenses/by-nc-sa/4.0/"

search:
  type: insight

comment:
  type: disqus
  shortname: "kains-note"

sidebar:
  left:
    sticky: false
  right:
    sticky: false

widgets:
  - type: profile
    position: left
    author: Kain
    author_title: 全栈 & 敏捷架构师
    location: 中国 · 海南
    avatar: /img/avatar.jpg
    avatar_rounded: true
    follow_link: "https://github.com/kainonly"
  - type: links
    position: left
    links:
      Ngx Bit: ""
      Gin: ""
      Hyperf: ""
      ThinkPHP: ""
  - type: categories
    position: left

  - type: recent_posts
    position: right
  - type: archives
    position: right
  - type: tags
    position: right

plugins:
  animejs: true
  back_to_top: true
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: "https://www.cookiesandyou.com/"
  google_analytics:
    tracking_id: G-J0NVPEBDTM
  progressbar: true

providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3/css/all.min.css
