sidebar:
  left:
    sticky: true
  right:
    sticky: false

widgets:
  - type: profile
    position: left
    author: Kain
    author_title: 全栈 & 敏捷架构师
    location: 中国 · 海南
    avatar: /img/avatar.jpg
    avatar_rounded: true
    follow_link: 'https://github.com/kainonly'
  - type: toc
    position: left
    index: false
  - position: left
    type: categories
  - type: tags
    position: left

